# Week 6 Day 1 - EDA

1. **Data Collection**
2. **Data Cleaning**
3. **Univariate Analysis**
4. Bivariate Analysis
5. Multivariate Analysis
6. Time Series Data
7. Dealing with Outliers and Missing Values

### Titanic dataset
https://www.kaggle.com/c/titanic/data

This datset was made for machine learning but provides some very interesting visualizations. I renamed the 'training' set as 'passengers' and  'gender_submission' file as 'survived'

In [7]:
import pandas as pd

#### Data Collection

In [14]:
#reading files
#df = pd.read_csv
passengersDF = pd.read_csv('Data_txtFiles/passengers.csv')
survivedDF = pd.read_csv('Data_txtFiles/survived.csv')

In [19]:
passengersDF.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [61]:
survivedDF.head()

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [63]:
passengersDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 423 entries, 0 to 422
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  423 non-null    int64
 1   Pclass       423 non-null    int64
 2   Name         423 non-null    object
 3   Sex          423 non-null    object
 4   Age          337 non-null    float64
 5   SibSp        423 non-null    int64
 6   Parch        423 non-null    int64
 7   Ticket       423 non-null    object
 8   Fare         422 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     423 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.5+ KB

#### Data Cleaning

In [66]:
#merge the two files
titanicDf = pd.merge(survivedDF, passengersDF, on = 'passengerId')

KeyError: 'passengerId'

In [70]:
titanicDF.head()

NameError: name 'titanicDF' is not defined

In [72]:
#get the info
titanicDf.info()

NameError: name 'titanicDf' is not defined

In [74]:
#get the datatypes
titanicDF.dtypes

NameError: name 'titanicDF' is not defined

In [76]:
#copy the dataframe
titanic_clean = titanicDf.copy()

NameError: name 'titanicDf' is not defined

In [78]:
# we have values that are not numbers

**Check for Duplicates**

subset : List of column names to check for duplication.

keep : Whether to keep first('first'), last('last'), or all (Flase) duplicate values

In [81]:
#.duplicated()
tittanic_clean.duplicated()

NameError: name 'tittanic_clean' is not defined

In [83]:
#make a new df with the duplicates
columnNames = ['passengerId

SyntaxError: unterminated string literal (detected at line 2) (2445620016.py, line 2)

In [85]:
#get the duplicates lable

In [87]:
# Drop duplicates

In [7]:
# get duplicates table again

In [8]:
#get info

**Value Consistancy**

In [9]:
#gender value counts

In [10]:
#1 set to lower case

In [11]:
#replace the other words

We only want whole round numbers - integers

In [12]:
#convert the age to integer

it is important taht we have nan values for now

In [13]:
#get the na ones to be an integer

In [14]:
#check the age

now we need to reset the Df back to what it was originally

In [37]:
#round them to the 0th position

In [15]:
#check unique

In [16]:
#check dtypes

### Univariate Analysis

In [17]:
# what do you use to plot numerical distributions?

**.plot()**

Make plots of Series or DataFrame. 

The kind of plot to produce:
- ‘line’ : line plot (default)
- ‘bar’ : vertical bar plot
- ‘barh’ : horizontal bar plot
- ‘hist’ : histogram
- ‘box’ : boxplot
- ‘kde’ : Kernel Density Estimation plot
- ‘density’ : same as ‘kde’
- ‘area’ : area plot
- ‘pie’ : pie plot
- ‘scatter’ : scatter plot (DataFrame only)
- ‘hexbin’ : hexbin plot (DataFrame only)

In [18]:
#pie chart or sex

In [19]:
# pie chart for survived

In [20]:
#what cabins were people in?

**.apply()**

Pandas.apply allow the users to pass a function and apply it on every single value of the Pandas series/column.

In [46]:
import numpy as np

In [47]:
#write a function to get cabin code
def getCode(cabinCode):
  if pd.isnull(cabinCode):
    pass
  else:
    return str(cabinCode)[0]

In [48]:
# apply the function

In [21]:
# get the value counts

In [22]:
#create a histogram

**.cut()**

Use cut when you need to segment and sort data values into bins. This function is also useful for going from a continuous variable to a categorical variable. For example, cut could convert ages to groups of age ranges. Supports binning into an equal number of bins, or a pre-specified array of bins.

In [51]:
#get the different age rage 
ranges = [0,18,65,np.inf]
group_names = ['Minor', 'Adult', 'Senior']

In [23]:
#get the age group value counts... Use this to classify different segments in data (ex: mammals, reptiles, amphibians).

In [ ]:
# Create AgeGroup column

In [24]:
#pie chart age group

### Save the Data

**.to_csv()**

Write object to a comma-separated values (csv) file.

**to_excel()**

Write object to an Excel sheet.

To write a single object to an Excel .xlsx file it is only necessary to specify a target file name. To write to multiple sheets it is necessary to create an ExcelWriter object with a target file name, and specify a sheet in the file to write to.

Multiple sheets may be written to by specifying unique sheet_name. With all data written to the file it is necessary to save the changes. Note that creating an ExcelWriter object with a file name that already exists will result in the contents of the existing file being erased.

**pickle**

[documentaion](https://docs.python.org/3/library/pickle.html)

Python pickle module is used for serializing and de-serializing a Python object structure. Any object in Python can be pickled so that it can be saved on disk. What Pickle does is it “serializes” the object first before writing it to a file. Pickling is a way to convert a Python object (list, dictionary, etc.) into a character stream. The idea is that this character stream contains all the information necessary to reconstruct the object in another Python script. It provides a facility to convert any Python object to a byte stream. This Byte stream contains all essential information about the object so that it can be reconstructed, or “unpickled” and get back into its original form in any Python. 

It is often used with really large datasets

<u>Advantages of Using Pickle in Python</u>

- **Recursive objects** (objects containing references to themselves): Pickle keeps track of the objects it has already serialized, so later references to the same object won’t be serialized again. (The marshal module breaks for this.)
- **Object sharing** (references to the same object in different places): This is similar to self-referencing objects. Pickle stores the object once, and ensures that all other references point to the master copy. Shared objects remain shared, which can be very important for mutable objects.
- **User-defined** classes and their instances: Marshal does not support these at all, but Pickle can save and restore class instances transparently. The class definition must be importable and live in the same module as when the object was stored.


<u>Disadvatages of Using Pickle in Python</u>

- **Python Version Dependency** : Data of picle is so sensitive to the version of Python that produced. Pickled object created with one version of - Python that might not be unpickled with a various versions.
- **Non-Readbl** : The format of pickle is binary and not easily readable or editable by humans. The contracts that are in JSON or XML format can be easily modified.
- **Large data inefficiency** : Large datasets can slow down the pickling and unpickling. Serialization might be more appropriate for such use-cases.

In [57]:
import pickle

In [ ]:
with open('Data_txtFiles/'